server:
  port: 8089

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
  datasource:
    url: jdbc:postgresql://localhost:5437/images_db
    username: alexgls
    password: AS04SERa1