volumes:
  users_db_data:
  students_grades_data:
  security_users_data:
  messaging_db_data:

networks:
  users-network:
    driver: bridge

services:
  users-database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - users_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - users-network

  students-grades-database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_STUDENTS_GRADES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - students_grades_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  security-users-database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_SECURITY_USERS_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - security_users_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  messaging-database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_MESSAGING_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - messaging_db_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1