server:
  port: 8087
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5436/messaging_db
    username: alexgls
    password: AS04SERa1

  liquibase:
    url: jdbc:postgresql://localhost:5436/messaging_db
    user: alexgls
    password: AS04SERa1
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:29092

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/.well-known/jwks.json

frontend:
  url: http://localhost:8090

services:
  auth-service: http://localhost:8085

values:
  page-size: 10