server:
  port: 8080

frontend:
  url: http://localhost:8090

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/.well-known/jwks.json

  # --- НАСТРОЙКА МАРШРУТОВ ---
  cloud:
    gateway:
      server:
        webflux:

          routes:
            # --- 1. Маршруты для AuthService (:8085) ---
            # Правило для публичных эндпоинтов (логин, ключи)
            - id: auth-public-route
              uri: http://localhost:8085
              predicates:
                - Path=/auth/**, /.well-known/jwks.json

            # Правило для защищенных эндпоинтов (пользователи)
            - id: users-service-route
              uri: http://localhost:8085
              predicates:
                - Path=/api/users/**

            # --- 2. Маршрут для сервиса сообщений (:8087) ---
            - id: messaging-service-route
              uri: http://localhost:8087
              predicates:
                # Все эти пути будут перенаправлены на сервис сообщений
                - Path=/api/attachments/**, /api/chats/**, /api/messages/**

            # --- 3. Маршрут для сервиса хранения файлов (:8088) ---
            - id: storage-service-route
              uri: http://localhost:8088
              predicates:
                - Path=/api/storage/**

            # --- 4. Маршрут для сервиса изображений в БД (:8089) ---
            - id: images-db-service-route
              uri: http://localhost:8089
              predicates:
                - Path=/api/images/**
